package lr.schedule.cayenne.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import lr.schedule.cayenne.Team;

/**
 * Class _Game was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Game extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> ARENA = new Property<String>("arena");
    public static final Property<Date> DATE_TIME = new Property<Date>("dateTime");
    public static final Property<Boolean> IN_PROGRESS = new Property<Boolean>("inProgress");
    public static final Property<Team> HOME_TEAM = new Property<Team>("homeTeam");
    public static final Property<Team> VISITING_TEAM = new Property<Team>("visitingTeam");

    public void setArena(String arena) {
        writeProperty("arena", arena);
    }
    public String getArena() {
        return (String)readProperty("arena");
    }

    public void setDateTime(Date dateTime) {
        writeProperty("dateTime", dateTime);
    }
    public Date getDateTime() {
        return (Date)readProperty("dateTime");
    }

    public void setInProgress(Boolean inProgress) {
        writeProperty("inProgress", inProgress);
    }
    public Boolean getInProgress() {
        return (Boolean)readProperty("inProgress");
    }

    public void setHomeTeam(Team homeTeam) {
        setToOneTarget("homeTeam", homeTeam, true);
    }

    public Team getHomeTeam() {
        return (Team)readProperty("homeTeam");
    }


    public void setVisitingTeam(Team visitingTeam) {
        setToOneTarget("visitingTeam", visitingTeam, true);
    }

    public Team getVisitingTeam() {
        return (Team)readProperty("visitingTeam");
    }


}
